---
title: "MetaProViz_MetaData_Analysis"
author: "Jannik Franken"
date: "16 7 2025"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 1. Install Rtools if you haven’t done this yet, using the appropriate version (e.g.windows or macOS).
# 2. Install the latest development version from GitHub using devtools
# devtools::install_github("https://github.com/saezlab/MetaProViz")

library(MetaProViz)

# dependencies that need to be loaded:
library(magrittr)
library(dplyr)
library(rlang)
library(tidyr)
library(tibble)
library(stringr)

# Please install the Biocmanager Dependencies:
# BiocManager::install("clusterProfiler")
# BiocManager::install("EnhancedVolcano")
```

```{r}
# Load the example data:
Tissue_Norm <- tissue_norm %>%
  column_to_rownames("Code")

Tissue_Norm
```

```{r}
Tissue_MetaData <- tissue_meta%>%
  column_to_rownames("Metabolite")

Tissue_MetaData
```






```{r}
MetaRes <- MetaProViz::metadata_analysis(data = Tissue_Norm[,-c(1:13)], 
                                         metadata_sample = Tissue_Norm[,c(2,4:5,12:13)],
                                         scaling = TRUE,
                                         percentage = 0.1,
                                         cutoff_stat= 0.05,
                                         cutoff_variance = 1
                                     )

MetaRes
```

```{r}
##1. Tissue_Type
TissueTypeList <- MetaRes[["res_summary"]] %>%
  filter(MainDriver_Term == "TISSUE_TYPE") %>%
  filter(`MainDriver_Sum(VarianceExplained)`>30) %>%
  select(feature) %>%
  pull()

# select columns tissue_norm that are in TissueTypeList if they exist
Input_Heatmap <- Tissue_Norm[ , names(Tissue_Norm) %in% TissueTypeList]  # c("N1-methylguanosine", "N-acetylalanine", "lysylmethionine")

# Heatmap: Metabolites that separate the demographics, like here TISSUE_TYPE
MetaProViz:::viz_heatmap(data = Input_Heatmap,
                         metadata_sample = Tissue_Norm[,c(1:13)],
                         metadata_info = c(color_Sample = list("TISSUE_TYPE")),
                         scale ="column",
                         plot_name = "MainDrivers"
                         )
```

```{r}
# Prepare the different selections
EarlyStage <- Tissue_Norm %>%
  filter(STAGE== "EARLY-STAGE")
LateStage <- Tissue_Norm %>%
  filter(STAGE=="LATE-STAGE")
Old <- Tissue_Norm %>%
  filter(AGE=="Old")
Young <- Tissue_Norm%>%
  filter(AGE=="Young")

DFs <- list("TissueType"= Tissue_Norm,
            "EarlyStage"= EarlyStage, 
            "LateStage"= LateStage, 
            "Old"= Old, 
            "Young"=Young
            )

# Run dma
ResList <- list()
for(item in names(DFs)){
  #Get the right DF:
  data <- DFs[[item]]

  message(paste("Running dma for", item))
  #Create folder for saving each comparison
  dir.create(paste(getwd(),"/MetaProViz_Results/dma/", sep=""), showWarnings = FALSE)
  dir.create(paste(getwd(),"/MetaProViz_Results/dma/", item, sep=""), showWarnings = FALSE)

  #Perform dma
  TvN <- MetaProViz::dma(data =  data[,-c(1:13)],
                   metadata_sample =  data[,c(1:13)],
                   metadata_info = c(Conditions="TISSUE_TYPE", Numerator="TUMOR" , Denominator = "NORMAL"),
                   shapiro=FALSE, #The data have been normalized by the company that provided the results and include metabolites with zero variance as they were all imputed with the same missing value.
                   path = paste(getwd(),"/MetaProViz_Results/dma/", item, sep=""))

  #Add Results to list
  ResList[[item]] <- TvN
}
```

```{r}
# Early versus Late Stage
MetaProViz::viz_volcano(plot_types = "Compare", 
                        data=ResList[["EarlyStage"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                        data2= ResList[["LateStage"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                        name_comparison= c(data="EarlyStage", data2= "LateStage"),
                        plot_name= "EarlyStage-TUMOR_vs_NORMAL compared to LateStage-TUMOR_vs_NORMAL",
                        subtitle= "Results of dma"
                        )
```

```{r}
# Young versus Old
MetaProViz::viz_volcano(plot_types = "Compare",
                        data=ResList[["Young"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                        data2= ResList[["Old"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                        name_comparison= c(data="Young", data2= "Old"),
                        plot_name= "Young-TUMOR_vs_NORMAL compared to Old-TUMOR_vs_NORMAL",
                        subtitle= "Results of dma"
                        )
```

```{r}
# Get the top changed metabolites
top_entries <- ResList[["TissueType"]][["dma"]][["TUMOR_vs_NORMAL"]] %>%
  arrange(desc(t.val)) %>%
  slice(1:25)%>%
  select(Metabolite)%>%
  pull()
bottom_entries <- ResList[["TissueType"]][["dma"]][["TUMOR_vs_NORMAL"]] %>%
  arrange(desc(t.val)) %>%
  slice((n()-24):n())%>%
  select(Metabolite)  %>%
  pull()

# Check if those overlap with the top demographics drivers
ggVennDiagram::ggVennDiagram(list(top = top_entries,
                                  Bottom = bottom_entries,
                                  TissueTypeList = TissueTypeList))+
  ggplot2::scale_fill_gradient(low = "blue", high = "red")
```

```{r}
MetaData_Metab <- merge(x=tissue_meta,
                   y= MetaRes[["res_summary"]][, c(1,5:6) ]%>%tibble::column_to_rownames("feature"),
                   by=0,
                   all.y=TRUE)%>%
  column_to_rownames("Row.names")

# Make a Volcano plot:
MetaProViz::viz_volcano(plot_types="Standard",
                       data=ResList[["TissueType"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                       metadata_feature =  MetaData_Metab,
                       metadata_info = c(color = "MainDriver_Term"),
                      plot_name= "TISSUE_TYPE-TUMOR_vs_NORMAL",
                       subtitle= "Results of dma" )
```

```{r}
#Load the feature metadata:
MetaboliteIDs <- Tissue_MetaData %>%
  rownames_to_column("Metabolite")%>%
  dplyr::rename("HMDB"= "Group_HMDB")%>%
  slice(1:577)# only keep entrys with trivial names

ccRCC_CompareIDs <- MetaProViz::compare_pk(data = list(Biocft = MetaboliteIDs |> dplyr::rename("Class"="SUPER_PATHWAY")),
                                           name_col = "Metabolite",
                                           metadata_info = list(Biocft = c("KEGG", "HMDB", "PUBCHEM")),
                                           plot_name = "Overlap of ID types in ccRCC data")
```

```{r}
Plot1_HMDB <- MetaProViz::count_id(MetaboliteIDs, "HMDB")
```

```{r}
Input_HMDB <- MetaboliteIDs %>%
  dplyr::filter(!is.na(HMDB)) %>% # ID in the measured data we want to use, hence we remove NA's
  dplyr::select("Metabolite", "HMDB", "SUPER_PATHWAY") # only keep relevant columns

# Add equivalent IDs:
tissue_meta_AddIDs_HMDB <- MetaProViz::equivalent_id(data= Input_HMDB,
                                                           metadata_info = c(InputID="HMDB"),# ID in the measured data, here we use the HMDB ID
                                                           from = "hmdb")
# Let's see how this has changed the number of entries:
tissue_meta_AddIDs_HMDB <- merge(x=MetaboliteIDs,
                                       y=tissue_meta_AddIDs_HMDB,
                                       by="HMDB",
                                       all.x=TRUE)

# Plot 2 after equivalent IDs where added
Plot2_HMDB <- MetaProViz::count_id(tissue_meta_AddIDs_HMDB, "AllIDs")
```

```{r}
no_hmdb <- dplyr::filter(MetaboliteIDs, is.na(HMDB) & (!is.na(PUBCHEM) | !is.na(KEGG)))

tissue_meta_translated_HMDB <-
  MetaProViz::translate_id(no_hmdb, metadata_info = list(InputID = "PUBCHEM", grouping_variable = "SUPER_PATHWAY"), from = "pubchem", to = "hmdb") |>
  extract2("TranslatedDF") |>
  rename(hmdb_from_pubchem = hmdb) |>
  MetaProViz::translate_id(metadata_info = list(InputID = "KEGG", grouping_variable = "SUPER_PATHWAY"), from = "kegg", to = "hmdb") |>
  extract2("TranslatedDF") |>
  rename(hmdb_from_kegg = hmdb)

# Here we combine the tables above, created by equivalent_id and translate_id:
Tissue_MetaData_HMDB <-
  left_join(
    tissue_meta_AddIDs_HMDB |>
      select(Metabolite = Metabolite.x, SUPER_PATHWAY = SUPER_PATHWAY.x, SUB_PATHWAY ,COMP_ID, PLATFORM, RI, MASS, CAS, PUBCHEM, KEGG,  HMDB, hmdb_from_equivalentid = AllIDs),
    tissue_meta_translated_HMDB |>
      select(COMP_ID, hmdb_from_pubchem, hmdb_from_kegg) |> mutate(across(starts_with("hmdb_from"), ~na_if(., ""))),
    by = 'COMP_ID'
  ) |>
  rowwise() |>
  mutate(hmdb_combined = list(unique(na.omit(unlist(stringr::str_split(across(starts_with("hmdb_from")), ",")))))) |>
  mutate(hmdb_combined = paste0(hmdb_combined, collapse = ',')) |>  # we concatenate by "," only for the sake of printing in notebook
  ungroup()

# Plot 3:
Plot3_HMDB <- MetaProViz::count_id(Tissue_MetaData_HMDB, "hmdb_combined")
```

```{r}
Plot1_KEGG <- MetaProViz::count_id(MetaboliteIDs, "KEGG")
```

```{r}

##################################################################################################################
Input_KEGG <- Tissue_MetaData_HMDB %>%
  dplyr::filter(!is.na(KEGG)) %>% # ID in the measured data we want to use, hence we remove NA's
  dplyr::select("Metabolite", "KEGG", "SUPER_PATHWAY") # only keep relevant columns

# Add equivalent IDs:
tissue_meta_AddIDs_KEGG <- MetaProViz::equivalent_id(data= Input_KEGG,
                                                metadata_info = c(InputID="KEGG"),# ID in the measured data, here we use the HMDB ID
                                                from = "kegg")

# Let's see how this has changed the number of entries:
tissue_meta_AddIDs_KEGG <- merge(x=Tissue_MetaData_HMDB,
                                 y=tissue_meta_AddIDs_KEGG,
                                 by="KEGG",
                                 all.x=TRUE)

Plot2_KEGG <-  MetaProViz::count_id(tissue_meta_AddIDs_KEGG, "AllIDs")
```

```{r}

###################################################################################################################
no_KEGG <- dplyr::filter(Tissue_MetaData_HMDB, is.na(KEGG) & (!is.na(PUBCHEM) | !is.na(HMDB)))

tissue_meta_translated_KEGG <-
  MetaProViz::translate_id(no_KEGG, metadata_info = list(InputID = "PUBCHEM", grouping_variable = "SUPER_PATHWAY"), from = "pubchem", to = "kegg") |>
  extract2("TranslatedDF") |>
  rename(kegg_from_pubchem = kegg) |>
  MetaProViz::translate_id(metadata_info = list(InputID = "HMDB", grouping_variable = "SUPER_PATHWAY"), from = "hmdb", to = "kegg") |>
  extract2("TranslatedDF") |>
  rename(kegg_from_hmdb = kegg)

# here we combine the tables above, created by equivalent_id and translate_id:
Tissue_MetaData_KEGG <-
  left_join(
    tissue_meta_AddIDs_KEGG |>
      select(Metabolite = Metabolite.x, SUPER_PATHWAY = SUPER_PATHWAY.x,SUB_PATHWAY, COMP_ID, PLATFORM, RI, MASS, CAS, PUBCHEM, HMDB=hmdb_combined , HMDB_Original = HMDB, hmdb_from_equivalentid, hmdb_from_kegg, hmdb_from_pubchem, , KEGG_Original = KEGG, kegg_from_equivalentid = AllIDs),
    tissue_meta_translated_KEGG |>
      select(COMP_ID, kegg_from_pubchem, kegg_from_hmdb) |> mutate(across(starts_with("kegg_from"), ~na_if(., ""))),
    by = 'COMP_ID'
  ) |>
  rowwise() |>
  mutate(KEGG= list(unique(na.omit(unlist(stringr::str_split(across(starts_with("kegg_from")), ",")))))) |>
  mutate(KEGG = paste0(KEGG, collapse = ',')) |>  # we concatenate by "," only for the sake of printing in notebook
  ungroup()

# Lets see the count now:
Plot3_KEGG <- MetaProViz::count_id(Tissue_MetaData_KEGG, "KEGG")
```

```{r}
Tissue_MetaData_Extended <-  Tissue_MetaData_KEGG[, c(1:10,19, 11:18)]%>%
  mutate(
    KEGG = ifelse(KEGG == "", NA, KEGG),
    HMDB = ifelse(HMDB == "", NA, HMDB)
  )

ccRCC_CompareIDs_Extended <- MetaProViz::compare_pk(data = list(Biocft = Tissue_MetaData_Extended |> dplyr::rename("Class"="SUPER_PATHWAY")),
                                                    name_col = "Metabolite",
                                                    metadata_info = list(Biocft = c("KEGG", "HMDB", "PUBCHEM")),
                                                    plot_name = "Overlap of ID types in ccRCC data")
```

```{r}
#Load Kegg pathways:
KEGG_Pathways <- metsigdb_kegg()

#check mapping with metadata

ccRCC_to_KEGGPathways <- MetaProViz::checkmatch_pk_to_data(data = Tissue_MetaData_Extended,
                                                           input_pk = KEGG_Pathways,
                                                           metadata_info = c(InputID = "KEGG", PriorID = "MetaboliteID", grouping_variable = "term"))

problems_terms <- ccRCC_to_KEGGPathways[["GroupingVariable_summary"]]%>%
  filter(!Group_Conflict_Notes== "None")
```

```{r}
# Select the cases where a feature has multiple IDs
multipleIDs <- ccRCC_to_KEGGPathways[["data_summary"]]%>%
  filter(original_count>1)
```

```{r}
SelectedIDs <- ccRCC_to_KEGGPathways[["data_summary"]]%>%
  #Expand rows where Action == KeepEachID by splitting `matches`
  dplyr::mutate(matches_split = if_else(Action_Specific == "KeepEachID", matches, NA_character_)) %>%
  separate_rows(matches_split, sep = ",\\s*") %>%
  mutate(InputID_select = if_else(Action_Specific  == "KeepEachID", matches_split, InputID_select)) %>%
  select(-matches_split) %>%
  #Select one ID for AcionSpecific==KeepOneID
  dplyr::mutate(InputID_select = case_when(
    Action_Specific == "KeepOneID" & matches == "C03460, C03722" ~ "C03722", # 2-Methylprop-2-enoyl-CoA versus Quinolinate. No evidence, hence we keep the one present in more pathways ( C03722=7 pathways, C03460=2 pathway)
    Action_Specific == "KeepOneID" & matches ==  "C00221, C00031" ~ "C00031", # These are D- and L-Glucose. We have human samples, so in this conflict we will maintain L-Glucose
    Action_Specific == "KeepOneID" & matches ==  "C17737, C00695" ~ "C00695", # Allocholic acid versus Cholic acid. No evidence, hence we keep the one present in more pathways (C00695 = 4 pathways, C17737 = 1 pathway)
    Action_Specific == "KeepOneID" ~ InputID_select,  # Keep NA where not matched manually
    TRUE ~ InputID_select
  )) 
```

```{r}
Tissue_MetaData_Extended <- merge(x= SelectedIDs %>%
                                        dplyr::select(KEGG, InputID_select),
                                  y= Tissue_MetaData_Extended,
                                  by= "KEGG",
                                  all.y=TRUE)
```

```{r}
# Since we have performed multiple comparisons (all_vs_HK2), we will run ORA for each of this comparison
DM_ORA_res<- list()

for(comparison in names(ResList)){#Res list includes the different comparisons we performed above <-
  #Ensure that the Metabolite names match with KEGG IDs or KEGG trivial names.
  dma_res <- merge(x= Tissue_MetaData_Extended,
                   y= ResList[[comparison]][["dma"]][["TUMOR_vs_NORMAL"]], 
                   by="Metabolite", 
                   all=TRUE)
  
  #Ensure unique IDs and full background --> we include measured features that do not have a KEGG ID.
  dma_res <- dma_res[,c(3,21:25)]%>%
    dplyr::mutate(InputID_select = if_else(
      is.na(InputID_select),
      paste0("NA_", cumsum(is.na(InputID_select))),
      InputID_select
      ))%>% #remove duplications and keep the higher Log2FC measurement
    group_by(InputID_select) %>%
    slice_max(order_by = Log2FC, n = 1, with_ties = FALSE) %>%
    ungroup()%>%
    remove_rownames()%>%
    tibble::column_to_rownames("InputID_select")
  
  #Perform ORA
  Res <- MetaProViz::standard_ora(data= dma_res, #Input data requirements: column `t.val` and column `Metabolite`
                                 metadata_info=c(pvalColumn="p.adj", percentageColumn="t.val", PathwayTerm= "term", PathwayFeature= "MetaboliteID"),
                                 input_pathway=KEGG_Pathways,#Pathway file requirements: column `term`, `Metabolite` and `Description`. Above we loaded the Kegg_Pathways using MetaProViz::Load_KEGG()
                                 pathway_name=paste0("KEGG_", comparison, sep=""),
                                 min_gssize=3,
                                 max_gssize=1000,
                                 cutoff_stat=0.01,
                                 cutoff_percentage=10)

  DM_ORA_res[[comparison]] <- Res

  #Select to plot:
  Res_Select <- Res[["ClusterGosummary"]]%>%
    filter(p.adjust<0.1)%>%
    #filter(pvalue<0.05)%>%
    filter(percentage_of_Pathway_detected>10)

  if(is.null(Res_Select)==FALSE){
     MetaProViz::viz_volcano(plot_types="PEA",
                       data= dma_res, #Must be the data you have used as an input for the pathway analysis
                       data2=as.data.frame(Res_Select )%>%dplyr::rename("term"="ID"),
                       metadata_info= c(PEA_Pathway="term",# Needs to be the same in both, metadata_feature and data2.
                                       PEA_stat="p.adjust",#Column data2
                                       PEA_score="GeneRatio",#Column data2
                                       PEA_Feature="MetaboliteID"),# Column metadata_feature (needs to be the same as row names in data)
                       metadata_feature= KEGG_Pathways,#Must be the pathways used for pathway analysis
                       plot_name= paste("KEGG_", comparison, sep=""),
                       subtitle= "PEA" )
  }
}
```

```{r}
MCAres <-  MetaProViz::mca_2cond(data_c1=ResList[["Young"]][["dma"]][["TUMOR_vs_NORMAL"]],
                                 data_c2=ResList[["Old"]][["dma"]][["TUMOR_vs_NORMAL"]],
                                 metadata_info_c1=c(ValueCol="Log2FC",StatCol="p.adj", cutoff_stat= 0.05, ValueCutoff=1),
                                 metadata_info_c2=c(ValueCol="Log2FC",StatCol="p.adj", cutoff_stat= 0.05, ValueCutoff=1),
                                 feature = "Metabolite",
                                 save_table = "csv",
                                 method_background="C1&C2"#Most stringend background setting, only includes metabolites detected in both comparisons
                                 )
```

```{r}
# Add metabolite information such as KEGG ID or pathway to results
MetaData_Metab <- merge(x=Tissue_MetaData,
                   y= MCAres[["MCA_2Cond_Results"]][, c(1, 14:15)]%>%tibble::column_to_rownames("Metabolite"),
                   by=0,
                   all.y=TRUE)%>%
  tibble::column_to_rownames("Row.names")

MetaProViz::viz_volcano(plot_types="Compare",
                       data=ResList[["Young"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                       data2= ResList[["Old"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                       name_comparison= c(data="Young", data2= "Old"),
                       metadata_feature =  MetaData_Metab,
                      plot_name= "Young-TUMOR_vs_NORMAL compared to Old-TUMOR_vs_NORMAL",
                       subtitle= "Results of dma",
                       metadata_info = c(individual = "SUPER_PATHWAY",
                                        color = "RG2_Significant"))

MetaProViz::viz_volcano(plot_types="Compare",
                       data=ResList[["Young"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                       data2= ResList[["Old"]][["dma"]][["TUMOR_vs_NORMAL"]]%>%tibble::column_to_rownames("Metabolite"),
                       name_comparison= c(data="Young", data2= "Old"),
                       metadata_feature =  MetaData_Metab,
                      plot_name= "Young-TUMOR_vs_NORMAL compared to Old-TUMOR_vs_NORMAL_Sub",
                       subtitle= "Results of dma",
                       metadata_info = c(individual = "SUB_PATHWAY",
                                        color = "RG2_Significant"))
```

```{r}
# Since we have performed multiple comparisons (all_vs_HK2), we will run ORA for each of this comparison
DM_ORA_res<- list()

KEGG_Pathways <- MetaProViz::metsigdb_kegg()

for(comparison in names(ResList)){
  dma_res <- merge(x= Tissue_MetaData_Extended,
                   y=ResList[[comparison]][["dma"]][["TUMOR_vs_NORMAL"]], 
                   by="Metabolite", 
                   all=TRUE)
  
  #Ensure unique IDs and full background --> we include measured features that do not have a KEGG ID.
  dma_res <- dma_res[,c(3,21:25)]%>%
    dplyr::mutate(InputID_select = if_else(
      is.na(InputID_select),
      paste0("NA_", cumsum(is.na(InputID_select))),
      InputID_select
      ))%>% #remove duplications and keep the higher Log2FC measurement
    group_by(InputID_select) %>%
    slice_max(order_by = Log2FC, n = 1, with_ties = FALSE) %>%
    ungroup()%>%
    remove_rownames()%>%
    tibble::column_to_rownames("InputID_select")
  
  
  #Perform ORA
  Res <- MetaProViz::standard_ora(data= dma_res, #Input data requirements: column `t.val` and column `Metabolite`
                                 metadata_info=c(pvalColumn="p.adj", percentageColumn="t.val", PathwayTerm= "term", PathwayFeature= "MetaboliteID"),
                                 input_pathway=KEGG_Pathways,#Pathway file requirements: column `term`, `Metabolite` and `Description`. Above we loaded the Kegg_Pathways using MetaProViz::Load_KEGG()
                                 pathway_name=paste0("KEGG_", comparison, sep=""),
                                 min_gssize=3,
                                 max_gssize=1000,
                                 cutoff_stat=0.01,
                                 cutoff_percentage=10)

  DM_ORA_res[[comparison]] <- Res

  #Select to plot:
  Res_Select <- Res[["ClusterGosummary"]]%>%
    filter(p.adjust<0.1)%>%
    #filter(pvalue<0.05)%>%
    filter(percentage_of_Pathway_detected>10)

  if(is.null(Res_Select)==FALSE){
     MetaProViz::viz_volcano(plot_types="PEA",
                       data= dma_res, #Must be the data you have used as an input for the pathway analysis
                       data2=as.data.frame(Res_Select )%>%dplyr::rename("term"="ID"),
                       metadata_info= c(PEA_Pathway="term",# Needs to be the same in both, metadata_feature and data2.
                                       PEA_stat="p.adjust",#Column data2
                                       PEA_score="GeneRatio",#Column data2
                                       PEA_Feature="MetaboliteID"),# Column metadata_feature (needs to be the same as row names in data)
                       metadata_feature= KEGG_Pathways,#Must be the pathways used for pathway analysis
                      plot_name= paste("KEGG_", comparison, sep=""),
                       subtitle= "PEA" )
  }
}
```




























